# Generated by Django 3.1.6 on 2021-02-10 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competencies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hardskill',
            name='skill_type',
        ),
        migrations.AddField(
            model_name='hardskill',
            name='skill_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='hard_skills', to='competencies.skilltype'),
            preserve_default=False,
        ),
    ]
